# Generated by Django 5.0.6 on 2024-06-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='decription',
            new_name='description',
        ),
    ]
